import '@shgysk8zer0/components/share-button.js';
import '@shgysk8zer0/components/current-year.js';
import '@shgysk8zer0/components/bacon-ipsum.js';
// import '@shgysk8zer0/components/gravatar-img.js';
import '@shgysk8zer0/components/install/prompt.js';
import '@shgysk8zer0/components/github/user.js';
import '@shgysk8zer0/components/app/list-button.js';
import '@shgysk8zer0/components/button/share-to.js';
// import '@shgysk8zer0/components/date-locale.js';
import '@kernvalley/components/ad.js';
import '@shgysk8zer0/components/weather/current.js';
// import '@shgysk8zer0/components/spotify/player.js';
import '@shgysk8zer0/components/youtube/player.js';
import '@shgysk8zer0/components/app/stores.js';
